---
title: "p8105_hw2_jdv2118"
output: github_document
---
```{r}
library(tidyverse)

library(readxl)

library(dplyr)

library(janitor)

library(tidyr)
```

# Problem 2

```{r}
mr_trash_wheel = 
  read_excel("data/Trash Wheel Collection Data.xlsx", "Mr. Trash Wheel", range = "A2:N550") %>%
  clean_names(dat = .) %>%
  mutate(sports_balls = 
  as.integer(
  round(sports_balls)), 
  trash_wheel = 1, 
  year =
  as.integer(year)) %>%
  drop_na(data = ., dumpster) %>%
  select(trash_wheel, everything())

head(mr_trash_wheel)

view(mr_trash_wheel)
```

```{r}
prof_trash_wheel = 
  read_excel("data/Trash Wheel Collection Data.xlsx", "Professor Trash Wheel", range = "A2:M97") %>%
  clean_names(dat = .) %>%
  mutate(trash_wheel = 2) %>%
  drop_na(data = ., dumpster) %>%
  select(trash_wheel, everything())

head(prof_trash_wheel)

view(prof_trash_wheel)
```

```{r}
trash_wheel_tidy =
  bind_rows(mr_trash_wheel, prof_trash_wheel)

view(trash_wheel_tidy)
#Do we need to arrange the columns in a certain order?
```

# Problem 3 

```{r}
pols =
  read_csv("data/pols-month.csv") %>%
  clean_names(dat = .) %>%
  separate(col = mon,   into = c("year", "month", "day"), sep = "-") %>%
  mutate(
    year = as.numeric(year), 
    month = as.numeric(month), 
    day = as.numeric(day),
    month = month.abb[as.numeric(month)],
    president = 
      if_else(prez_gop == 1, 'gop', 'dem')) %>% 
    select(-prez_dem, -prez_gop, -day) %>%
  arrange(year, month)

#How do I change month, day, and year to numeric?
head(pols)
view(pols)

snp = 
  read_csv("data/snp.csv") %>%
  clean_names(dat = .) %>%
  separate(col = date,   into = c("month", "day", "year"), sep = "/") %>%
  mutate(
    year = as.numeric(year), 
    month = as.numeric(month), 
    day = as.numeric(day),
    month = month.abb[as.numeric(month)]) %>% 
    select(-day) %>%
  arrange(year, month) %>%
  select(year, month, everything())

#How do I change month, day, and year to numeric (as numeric twice for month) and redundant code?
#How do I add the two digits of year to every value within the year column?
head(snp)
view(snp)

unemployment =
  read_csv("data/unemployment.csv") %>%
  clean_names(dat = .) %>%
  pivot_longer(
    unemployment, 
    Jan:Dec,
    names_to = "month", 
    values_to = "unemployment_percentage"
    )

#how do I fix the pivot_longer error?
head(unemployment)
view(unemployment)
```

```{r}
pols_snp =
  bind_rows(pols, snp)

#Is this correct for merging snp into pols?

pols_snp_unemployment = 
  bind_rows(pols_snp, unemployment)

#should we have kept the original names for the result dataframes?
view(pols)
```


